// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1arN85fDvKBPjOseEmiB6IlNVNsJjxEA',
    appId: '1:943371770075:web:ef42058a42b303c7f714fe',
    messagingSenderId: '943371770075',
    projectId: 'happy-tales-app',
    authDomain: 'happy-tales-app.firebaseapp.com',
    storageBucket: 'happy-tales-app.appspot.com',
    measurementId: 'G-224TCX6FVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGkY0wrx9fTMk_diGTd4wIl0asz36xtTg',
    appId: '1:943371770075:android:ba0954d41045529df714fe',
    messagingSenderId: '943371770075',
    projectId: 'happy-tales-app',
    storageBucket: 'happy-tales-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYwgwbMpdNNACpw0t90QyewrNlVEcgwyc',
    appId: '1:943371770075:ios:cbc1e840134e227ef714fe',
    messagingSenderId: '943371770075',
    projectId: 'happy-tales-app',
    storageBucket: 'happy-tales-app.appspot.com',
    iosBundleId: 'com.example.happytales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYwgwbMpdNNACpw0t90QyewrNlVEcgwyc',
    appId: '1:943371770075:ios:cbc1e840134e227ef714fe',
    messagingSenderId: '943371770075',
    projectId: 'happy-tales-app',
    storageBucket: 'happy-tales-app.appspot.com',
    iosBundleId: 'com.example.happytales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1arN85fDvKBPjOseEmiB6IlNVNsJjxEA',
    appId: '1:943371770075:web:e67fcd350d3a3ecdf714fe',
    messagingSenderId: '943371770075',
    projectId: 'happy-tales-app',
    authDomain: 'happy-tales-app.firebaseapp.com',
    storageBucket: 'happy-tales-app.appspot.com',
    measurementId: 'G-HX77W7Y6QS',
  );
}
